### PR TITLE
DRS integration in sctplb & fixing call distribution

### PR DESCRIPTION
**Pull request by thakurajayL**

### CODE REVIEW

**Comment by gab-arrobo** [comment]
Please take a look at the comments I added in PR #7. Several of the comments there are aplicable to this PR?
BTW, why did you create a new PR instead of just updating PR #7?

**Comment by thakurajayL** [comment]
> Please take a look at the comments I added in PR #7. Several of the comments there are aplicable to this PR? BTW, why did you create a new PR instead of just updating PR #7?

I have taken all applicable comments in this PR. My repository was completely screwed up.

**Comment by gab-arrobo** [comment]
ok to test

**Review by gab-arrobo — CHANGES_REQUESTED** [review]
+1 (tested changes with AiaB) but you need to execute `go mod tidy` and include the updated go.mod and go.sum files in your PR. The issue is not shown when running inside Docker because Dockerfile is doing it for you:
```Dockerfile
RUN cd $GOPATH/src/sctplb && go mod tidy && go install
```

Moreover, I am thinking in removing `go mod tidy` from the Dockerfile such that this issue is NOT "hidden". I am planning to update my PR as follows. So, the source code is aligned to what Dockerfile is using to create the image. What do you think?
```Diff
- RUN cd $GOPATH/src/sctplb && go mod tidy && go install
+ RUN cd $GOPATH/src/sctplb && go install
```

**Review by gab-arrobo — APPROVED** [review]
+1 (tested changes with AiaB)

**Pull request merged**
